---
- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present

- name: Ensure .my.cnf file exists for root
  copy:
    dest: "/root/.my.cnf"
    content: |
      [client]
      user=root
      password={{ db_root_password }}
    mode: '0600'
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Ensure MySQL is running
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Disable plugin authentication for root user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: ""
    user: root
    host: localhost
    plugin: mysql_native_password
    state: present
  ignore_errors: yes

- name: Set root user password
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: ""
    user: root
    password: "{{ db_root_password }}"
    host: localhost
    state: present
  ignore_errors: yes

- name: Remove anonymous user accounts
  mysql_user:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: ''
    host_all: yes
    state: absent

- name: Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: test
    state: absent

- name: Create WordPress database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: root

- name: Create WordPress user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "wordpress.*:ALL,GRANT"
    state: present
