---
- hosts: test_servers
  become: yes
  vars_files:
    - wordpress_vars.yml
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure .my.cnf file exists for root
      copy:
        dest: "/root/.my.cnf"
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}
        mode: '0600'
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install PHP and extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Create Document Root
      file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Check if WordPress archive already exists
      stat:
        path: /tmp/latest.tar.gz
      register: wp_archive

    - name: Download WordPress archive
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz
      when: not wp_archive.stat.exists

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes
        creates: "/var/www/html/wordpress"

    - name: Ensure MySQL is running
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Disable plugin authentication for root user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: ""
        user: root
        host: localhost
        plugin: mysql_native_password
        state: present
      ignore_errors: yes

    - name: Set root user password
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: ""
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present
      ignore_errors: yes

    - name: Remove anonymous user accounts
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ''
        host_all: yes
        state: absent

    - name: Remove test database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: absent

    - name: Create WordPress database
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: root

    - name: Create WordPress user
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "wordpress.*:ALL,GRANT"
        state: present

    - name: Copy WordPress config file
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Enable mod_rewrite for Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Set up Apache virtual host for WordPress
      template:
        src: wordpress.conf.j2
        dest: /etc/apache2/sites-available/wordpress.conf
      notify:
        - restart apache

    - name: Enable WordPress site
      command: a2ensite wordpress.conf
      notify:
        - restart apache

    - name: Disable default site
      command: a2dissite 000-default.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
